version: '3'
services:
  adonis:
    container_name: adonis
    build: .
    command: adonis serve --dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:12.4
    environment:
      POSTGRES_DB: nlw
      POSTGRES_USER: nlw-user
      POSTGRES_PASSWORD: ignite
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
