version: '3'
services:
  web:
    build: .
    command: adonis serve --dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:12.4
    environment:
      POSTGRES_DB: nlw
      POSTGRES_USER: nlw-user
      POSTGRES_PASSWORD: ignite
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
